---
title: "SPARS trial A and B"
subtitle: "Stability and reproducibility of the stimulus-response relationship"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  html_document:
    keep_md: true
    theme: yeti
    hightlight: pygments
    toc: true
    toc_depth: 5
    toc_float: true
    code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)
library(lqmm)

# Set ggplot theme (since I've loaded sjPlot)
sjPlot::set_theme(base = theme_bw())

# Colour palette
cb_palette <- c('#F0E442', '#0072B2', '#D55E00', '#CC79A7')

# knitr setup
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.retina = 2,
                      fig.height = 7,
                      fig.width = 7,
                      fig.align = 'center',
                      fig.path = 'figures/5-reproducibility/')
```

----

This analysis examines the stability and reproducibility of the stimulus-response characateristics of the SPARS.

The procedure followed is as follows:

1. To assess the reproducibility of the stimulus-response relationship, we explored whether the responses of the replication cohort (Trial B) lay within the 95% prediction interval of the original stimulus-response function (Trial A). 

2. To assess the stability of the relationship, we bootstrapped 20 samples each for 3 'cohort' sizes (n = 5, 10 and 15 participants), and explored the stimulus-response relationship across these bootstrapped samples.

----

# Import and inspect data
```{r import}
# Import and inspect
## Trial A
data_A <- read_rds('./data-cleaned/SPARS_A.rds')
glimpse(data_A)

## Trial B
data_B <- read_rds('./data-cleaned/SPARS_B.rds')
glimpse(data_B)
```

----

# Define Tukey trimean function

```{r tukey}
# Define tri.mean function
tri.mean <- function(x) {
  # Calculate quantiles
  q1 <- quantile(x, probs = 0.25, na.rm = TRUE)[[1]]
  q2 <- median(x, na.rm = TRUE)
  q3 <- quantile(x, probs = 0.75, na.rm = TRUE)[[1]]
  # Calculate trimean
  tm <- (q2 + ((q1 + q3) / 2)) / 2
  # Convert to integer
  tm <- as.integer(round(tm))
  return(tm)
}
``` 

----

# Objective 1: Reproducibility

### Clean data
```{r clean_obj1}
############################################################
#                                                          #
#                       Trial A data                       #
#                                                          #
############################################################
data_tmA <- data_A %>%
    # Select columns
    select(PID, intensity, rating) %>%
    # Calculate tri.mean
    group_by(PID, intensity) %>% 
    summarise(tri_mean = tri.mean(rating))
    
############################################################
#                                                          #
#                       Trial B data                       #
#                                                          #
############################################################
data_B %<>%
    # Only retain SPARS data
    filter(scale == 'SPARS')

data_tmB <- data_B %>% 
    # Select columns
    select(PID, intensity, rating) %>% 
    # Calculate tri.mean
    group_by(PID, intensity) %>% 
    summarise(tri_mean = tri.mean(rating))
```

### Trial A 95% prediction interval vs 'raw' Trial B comparison

#### Exploratory plots

```{r explore_predRAW, fig.width = 9}
############################################################
#                                                          #
#                    Trial A quantiles                     #
#                                                          #
############################################################
# Quantile model with 2.5, 25, 50, 75, and 97.5% quantiles
qmm <- lqmm(fixed = tri_mean ~ poly(intensity, 3),
            random = ~ intensity,
            group = PID,
            data = data_tmA,
            tau = c(0.025, 0.975))

# Get predicted values
## Level 0 (conditional, note difference to the lmer diagnostics)
quant_predict <- as.data.frame(predict(qmm, level = 0))
names(quant_predict) <- paste0('Q', c(2.5, 97.5))

# Join with 'data_tmA'
data_tmA %<>%
  bind_cols(quant_predict)

# Trim prediction to upper and lower limits of the scale
data_tmA %<>%
  mutate_if(is.numeric,
            funs(ifelse(. > 50,
                        yes = 50,
                        no = ifelse(. < -50,
                                    yes = -50,
                                    no = .))))

############################################################
#                                                          #
#             Trial B within Trial A quantiles             #
#                                                          #
############################################################
# Process data
raw_predictionPlots <- data_B %>%
    group_by(PID) %>%
    nest() %>%
    # Plot data
    mutate(plots = map2(.x = data,
                        .y = PID,
                       ~ ggplot() +
                           geom_ribbon(data = data_tmA,
                                       aes(x = intensity,
                                           ymin = `Q2.5`,
                                           ymax = `Q97.5`),
                                       fill = '#CCCCCC') +
                           geom_point(data = .x,
                                      aes(x = intensity,
                                          y = rating),
                                      colour = cb_palette[[2]]) +
                           geom_smooth(data = .x,
                                      aes(x = intensity,
                                          y = rating),
                                      colour = cb_palette[[2]],
                                      method = 'loess',
                                      se = FALSE) +
                           geom_hline(yintercept = 0,
                                      linetype = 2) +
                           labs(title = paste0(.y, ': Raw SPARS ratings vs stimulus intensity from Trial B, facetted by experimental block'),
                                subtitle = 'Blue circles: raw data points | Blue lines: loess curve | Grey area: 95% prediction interval of the Trial A dataset\nThe prediction interval extends to the limits of the range of stimulus intensities used in Trial A (1 to 4J)',
                                x = 'Stimulus intensity (J)',
                                y = 'SPARS rating [-50 to 50]') +
                           scale_y_continuous(limits = c(-50, 50)) +
                           scale_x_continuous(limits = c(1, 5)) +
                           facet_wrap(~block_number, ncol = 2))) 

# Print output
walk(.x = raw_predictionPlots$plots, ~print(.x))
```

#### Quantification

```{r quant_predRAW}
# Get Trial A prediction interval bounds for each stimulus intensity 
pred_bounds <- data_tmA %>%
    ungroup() %>%
    select(intensity, Q2.5, Q97.5) %>%
    # `base::unique` giving 15 instead of 13 rows, so move to plan B
    group_by(intensity) %>%
    summarise(Q2.5 = mean(Q2.5),
              Q97.5 = mean(Q97.5))

# View prediction interval bounds
knitr::kable(pred_bounds,
             caption = '95% prediction interval bounds for Trial A (cubic model) at each stimulus intensity', 
             col.names = c('Stimulus intensity', 'Q2.5', 'Q97.5'), 
             digits = 2,
             align = 'lrr')

# Filter Trial B data to the stimulus range used in Trial A (1 to 4J)
data_BReduced <- data_B %>% 
    ungroup() %>% 
    filter(intensity >= 1 & intensity <= 4)

# Calculate whether raw points are inside or outside the 
# prediction interval at each stimulus intensity
foo <- data_BReduced %>% 
    # Nest data by stimulus intensity
    group_by(intensity) %>%
    nest() %>%
    arrange(intensity) %>%
    # Join with pred_bounds
    left_join(pred_bounds) %>% 
    # Perform calculation 
    mutate(analysis = pmap(.l = list(data, Q2.5, Q97.5),
                           ~ mutate(.data = ..1,
                                    included = case_when(
                                        rating >= ..2 & rating <= ..3 ~ 'yes',
                                        TRUE ~ 'no'
                                    )))) %>%
    # Drop columns and bring it all back together
    select(-data, -(starts_with('Q'))) %>%
    unnest()
    
# Plot
foo %>%
    # Calculate counts
    group_by(intensity, included) %>% 
    summarise(count = n()) %>%
    ungroup() %>% 
    mutate(intensity = sprintf('%.2f', intensity)) %>%
    # Plot
    ggplot(data = .) +
    aes(y = count,
        x = intensity,
        fill = included) +
    geom_bar(stat = 'identity', 
             position = position_fill()) +
    labs(title = 'Proportion of raw SPARS ratings falling with the 95% prediction interval of the Trial A (cubic model)',
         x = 'Stimulus intensity (J)',
         y = 'Proportion of ratings') +
    scale_fill_manual(name = 'Included in interval: ',
                      values = rev(cb_palette[2:3])) +
    theme(legend.position = 'top')
```

### Trial A 95% prediction interval vs 'trimean' Trial B comparison

#### Plots

```{r plot_predTM, fig.width = 9}
# Process data
tm_predictionPlots <- data_tmB %>%
    group_by(PID) %>%
    nest() %>%
    # Plot data
    mutate(plots = map2(.x = data,
                        .y = PID,
                       ~ ggplot() +
                           geom_ribbon(data = data_tmA,
                                       aes(x = intensity,
                                           ymin = `Q2.5`,
                                           ymax = `Q97.5`),
                                       fill = '#CCCCCC') +
                           geom_point(data = .x,
                                      aes(x = intensity,
                                          y = tri_mean),
                                      colour = cb_palette[[2]]) +
                           geom_smooth(data = .x,
                                      aes(x = intensity,
                                          y = tri_mean),
                                      colour = cb_palette[[2]],
                                      method = 'loess',
                                      se = FALSE) +
                           geom_hline(yintercept = 0,
                                      linetype = 2) +
                           labs(title = paste0(.y, ': Tukey trimeans of raw SPARS ratings vs stimulus intensity from Trial B, facetted by experimental block'),
                                subtitle = 'Blue circles: Tukey trimean data points | Blue lines: loess curve | Grey area: 95% prediction interval of the Trial A dataset\nThe prediction interval extends to the limits of the range of stimulus intensities used in Trial A (1 to 4J)',
                                x = 'Stimulus intensity (J)',
                                y = 'SPARS rating [-50 to 50]') +
                           scale_y_continuous(limits = c(-50, 50)) +
                           scale_x_continuous(limits = c(1, 5)))) 

# Print output
walk(.x = tm_predictionPlots$plots, ~print(.x))
```

# Session information
```{r session_info}
sessionInfo()
```
