---
title: "SPARS trial A"
subtitle: "Visual inference of the association between stimulus intensity and SPARS rating"
author: "Peter Kamerman"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  html_document:
    keep_md: true
    theme: yeti
    hightlight: pygments
    toc: true
    toc_depth: 5
    toc_float: true
    code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)
library(modelr)

# Set ggplot theme (since I've loaded sjPlot)
sjPlot::set_theme(base = theme_bw())

# Colour palette
cb_palette <- c('#F0E442', '#0072B2', '#D55E00', '#CC79A7')

# knitr setup
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.retina = 2,
                      fig.height = 7,
                      fig.width = 7,
                      fig.align = 'center',
                      fig.path = 'figures/A-visual-inference/')
```

----

This analysis uses the line-up method of visual inference to assess the relationship between stimulus intensity and SPARS rating. The method involves placing a plot of the the observed data in a line-up of 19 other datasets derived from the observed data, but where any association between the dependent and independent variable has been broken using permutation (i.e., the new data are NULL models).

----

# Import and inspect data
```{r import}
# Import
data <- read_rds('./data-cleaned/SPARS_A.rds')

# Inspect
glimpse(data)
```

----

# Clean data

```{r clean}
# Define Tukey trimean function
tri.mean <- function(x) {
  # Calculate quantiles
  q1 <- quantile(x, probs = 0.25, na.rm = TRUE)[[1]]
  q2 <- median(x, na.rm = TRUE)
  q3 <- quantile(x, probs = 0.75, na.rm = TRUE)[[1]]
  # Calculate trimean
  tm <- (q2 + ((q1 + q3) / 2)) / 2
  # Convert to integer
  tm <- as.integer(round(tm))
  return(tm)
}

# Define sampling function
sampler <- function(x = data_ref, 
                    y = data_nest, 
                    size = 5, 
                    by = 'PID') {
    foo <- sample_n(x, size = size) %>%
        inner_join(x = ., y = y, by = by) %>%
        arrange(PID)
    return(foo)
}

# Calculate trimeans
data_tm <- data %>%
    # Select columns
    select(PID, intensity, rating) %>%
    # Calculate tri.mean
    group_by(PID, intensity) %>% 
    summarise(tri_mean = tri.mean(rating))

# Generated nested table of data_tm
data_nest <- data_tm %>% 
    group_by(PID) %>% 
    nest()

# Sampling reference
data_ref <- select(data_nest, PID)
```

----

# Senario 1 (n = 5)

```{r n5_sampling}
# Generate data
n5 <- map(1:20,
    ~ sampler(size = 5))

# Unnest data
n5 <- map(.x = n5,
          ~ unnest(.x))

n5
```

----

# Session information
```{r session_info}
sessionInfo()
```
